services:
  omniscan:
    build: .
    restart: unless-stopped 
    container_name: omniscan 
    image: omniscan:latest
    hostname: omniscan 
    command: python -m omniscan_pkg.main --watch
    ports:
      - 8085:8000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes: 
      - /media/docker/data/omniscan:/app/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt:rslave
      - /media:/media:rslave
    networks:
      - pangolin

networks:
  pangolin:
    external: true